import { ArtistData } from "@/types";

export const artists: ArtistData[] = [
  // Progressive / Breaks / Club lineage
  { slug: "sasha", name: "Sasha", bio: "Sasha's deejaying rewired progressive house from warehouse afterthought into arena ritual. With Digweed, he built the template that made electronic music intimate in 15,000-capacity rooms.", links: { website: "https://sasha.com" }, relatedArtists: ["john-digweed"] },
  { slug: "john-digweed", name: "John Digweed", bio: "John's production chops are secondary to his deejaying genius. His four-hour sets didn't just move dancefloors, they became the blueprint for how progressive house could narrate emotional depth.", links: { website: "https://johndigweed.com" }, relatedArtists: ["sasha", "hernan-cattaneo"] },
  { slug: "hernan-cattaneo", name: "Hernan Cattaneo", bio: "Buenos Aires legend who brought Southern Hemisphere perspective to techno's North Atlantic axis. His ability to read a floor and construct narrative across four hours remains unmatched.", links: { website: "https://www.hernancattaneo.com" }, relatedArtists: ["john-digweed"] },
  { slug: "james-holden", name: "James Holden", bio: "James is both technician and philosopher. His polyrhythmic deep house production and thoughtful deejaying have helped define what progressive music becomes when it learns to think.", links: { website: "https://www.jamesholden.com" }, relatedArtists: ["nathan-fake"] },
  { slug: "nathan-fake", name: "Nathan Fake", bio: "Norfolk's Nathan creates fractured, detailed sound design that operates at the nexus of deep house and techno. His tracks reward repeated listening on expensive speakers.", links: { website: "https://nathanfake.bandcamp.com" }, relatedArtists: ["james-holden"] },
  { slug: "bedrock-artist", name: "Bedrock", bio: "Digweed and Muir's legendary London club defined deep house for a generation. A venue that felt like a temple, a sound system that was an instrument.", links: {}, relatedArtists: ["john-digweed"] },
  { slug: "paul-van-dyk", name: "Paul Van Dyk", bio: "German trance architect whose symphonic breakdowns and euphoric builds defined 1990s club transcendence. His marathon DJ sets were spiritual experiences disguised as dancefloor marathons.", links: { website: "https://www.paulvandyk.com" }, relatedArtists: ["paul-oakenfold"] },
  { slug: "paul-oakenfold", name: "Paul Oakenfold", bio: "Oakenfold brought Balearic bliss and chemical breakdown narratives to mainstream consciousness. His Perfecto label became shorthand for uplifting trance during electronic music's stratospheric rise.", links: { website: "https://www.pauloakenfold.com" }, relatedArtists: ["paul-van-dyk"] },
  { slug: "crystal-method", name: "Crystal Method", bio: "Scott Kirkland and Ethan Nadel bridged Vegas energy with LA production craft. Tweekend and Vegas proved that big-beat electronica could be both bombastic and mysteriously textured.", links: { website: "https://www.crystalmethodonline.com" }, relatedArtists: [] },
  { slug: "noel-sanger", name: "Noel Sanger", bio: "Prolific underground producer whose detailed, jazz-inflected house and techno work remains underrated in discourse. A craftsperson of deep listening and sophisticated harmony.", links: {}, relatedArtists: [] },
  { slug: "shiloh", name: "Shiloh", bio: "Mysterious New York producer whose sparse, introspective techno operates in shadow and restraint. His releases feel like confidences whispered in dark rooms.", links: { bandcamp: "https://shilohmusic.bandcamp.com" }, relatedArtists: [] },
  { slug: "madoka", name: "Madoka", bio: "Subtle Tokyo producer whose deeply minimal, stripped-to-silence compositions explore the space between sound and absence. Patience as an artistic statement.", links: { bandcamp: "https://madokamusic.bandcamp.com" }, relatedArtists: [] },
  { slug: "habersham", name: "Habersham", bio: "Atlanta's James Blake connection brings emotional vulnerability to beatless composition. His modular pieces feel like private meditation sessions made audible.", links: { bandcamp: "https://habersham.bandcamp.com" }, relatedArtists: [] },
  { slug: "lexicon-avenue", name: "Lexicon Avenue", bio: "UK producer whose intricate, sample-layered work bridges breaks and ambient territories. Dense textural palettes that reward deep listening and sustained attention.", links: { bandcamp: "https://lexicon-avenue.bandcamp.com" }, relatedArtists: [] },
  { slug: "steve-lawler", name: "Steve Lawler", bio: "British deep house virtuoso whose meticulous sound design and rhythmic sophistication helped redefine techno for cerebral dancefloors. His Visionquest label remains a beacon of taste.", links: { website: "https://www.stevelawler.com" }, relatedArtists: ["lee-burridge"] },
  { slug: "lee-burridge", name: "Lee Burridge", bio: "Bristol's Lee blends hypnotic minimal techno with meditative depth. His residencies and radio work have become spiritual practice for electronic music listeners worldwide.", links: { website: "https://leeburridge.com" }, relatedArtists: ["steve-lawler"] },

  // Ambient / IDM / Warp lineage
  { slug: "aphex-twin", name: "Aphex Twin", bio: "Richard D. James redefined IDM as both visceral dance floor weapon and abstract sculptural art. His uncompromising refusal to explain his music is the entire point.", links: { bandcamp: "https://aphextwin.bandcamp.com", website: "https://warp.net/artists/aphex-twin" }, relatedArtists: ["squarepusher", "autechre"] },
  { slug: "boards-of-canada", name: "Boards of Canada", bio: "Scottish brothers Mike Sandison and Marcus Eoin craft hypnagogic pop that feels like searching through lost analog tapes. Music Has the Right to Children is modular synth parenthood.", links: { website: "https://www.music-man.com" }, relatedArtists: ["aphex-twin"] },
  { slug: "autechre", name: "Autechre", bio: "Sean Booth and Rob Brown treat synthesis as algorithmic poetry. Incunabula was pure alien machinery; 30 years later they're still the most uncompromising voices in generative music.", links: { bandcamp: "https://autechre.bandcamp.com" }, relatedArtists: ["aphex-twin"] },
  { slug: "burial", name: "Burial", bio: "Will Bevan pulled UK garage and UK funky into spectral echo chambers. His half-speed breakbeats and pitched-down vocals rewired how producers think about time and texture.", links: { website: "https://burial.bandcamp.com" }, relatedArtists: ["four-tet"] },
  { slug: "squarepusher", name: "Squarepusher", bio: "Tom Jenkinson's jazz fusion meets circuit-bent IDM. His live shows are physical marathons of rhythm and texture, proving that electronically-generated sound could demand the same virtuosity as acoustic performance.", links: { bandcamp: "https://squarepusher.bandcamp.com" }, relatedArtists: ["aphex-twin"] },
  { slug: "mu-ziq", name: "\u00b5-Ziq", bio: "Mike Paradinas built Planet Mu as a laboratory for IDM excess. His hyperactive breakbeats and acid spirals proved that intelligent dance music could also be kinetic mayhem.", links: { bandcamp: "https://muziq.bandcamp.com" }, relatedArtists: ["aphex-twin"] },
  { slug: "oneohtrix-point-never", name: "Oneohtrix Point Never", bio: "Daniel Lopatin merges chopped Muzak, spiritual jazz, and cutting-edge synthesis. His work haunts the threshold between pop accessibility and pure experimental density.", links: { bandcamp: "https://oneohtrixpointnever.bandcamp.com" }, relatedArtists: ["tim-hecker"] },
  { slug: "tim-hecker", name: "Tim Hecker", bio: "Canadian sound artist whose microscopic detail work and processing chains turn field recordings and synth noise into architectural sculptures. His silences are as dense as his crescendos.", links: { bandcamp: "https://timhecker.bandcamp.com" }, relatedArtists: ["oneohtrix-point-never", "fennesz"] },
  { slug: "four-tet", name: "Four Tet", bio: "Kieran Hebden's work ethic is legendary, his touch invisible. He remixed everyone, produced the unclassifiable, and proved that intricate electronic music could move rooms full of people.", links: { bandcamp: "https://fourtet.bandcamp.com" }, relatedArtists: ["burial", "nicolas-jaar"] },
  { slug: "nicolas-jaar", name: "Nicolas Jaar", bio: "Chilean electronic musician with classical training. His Space Is Only Noise remains a touchstone for how techno could be introspective, detailed, and emotionally visceral.", links: { bandcamp: "https://nicolasjaar.bandcamp.com" }, relatedArtists: ["four-tet"] },
  { slug: "actress", name: "Actress", bio: "Darren Cunningham's industrial aesthetic meets danceable abstraction. His distorted, granular textures conjure post-industrial ghosts on the darkest dancefloors.", links: { bandcamp: "https://actress.bandcamp.com" }, relatedArtists: [] },
  { slug: "caterina-barbieri", name: "Caterina Barbieri", bio: "Italian composer of modular systems and mathematical gesture. Her work uses Buchla and Serge synthesizers as instruments for exploring repetition, recursion, and the threshold between order and chaos.", links: { bandcamp: "https://caterinalabarbieri.bandcamp.com" }, relatedArtists: ["kali-malone"] },
  { slug: "kali-malone", name: "Kali Malone", bio: "Kali's harmonic synthesis work excavates the sacred frequencies buried in analog oscillators. Her installations and vinyl releases are meditative passages through pure electromagnetic sound.", links: { bandcamp: "https://kalimalone.bandcamp.com" }, relatedArtists: ["sarah-davachi", "caterina-barbieri"] },
  { slug: "sarah-davachi", name: "Sarah Davachi", bio: "Sarah's organ and modular works inhabit the space between hymnal and spectralism. Her long-form compositions invite deep listening, rewarding sustained attention with harmonic revelation.", links: { bandcamp: "https://sarahdavachi.bandcamp.com" }, relatedArtists: ["kali-malone"] },
  { slug: "lorenzo-senni", name: "Lorenzo Senni", bio: "Italian minimalist whose meticulously tuned sine wave excursions explore the mathematics of pitch and perception. His installations and live sets exist in suspended hypnotic states.", links: { bandcamp: "https://lorenzosenni.bandcamp.com" }, relatedArtists: [] },
  { slug: "kara-lis-coverdale", name: "Kara-Lis Coverdale", bio: "Vancouver's Kara-Lis builds immersive electronic environments from synthesizers, field recordings, and resonant architectures. Her work feels like walking through someone else's memory.", links: { bandcamp: "https://kara-lis.bandcamp.com" }, relatedArtists: [] },
  { slug: "loraine-james", name: "Loraine James", bio: "South London's Loraine creates glitchy, polyrhythmic abstractions that blur between footwork, ambient, and pure signal corruption. Her music refuses easy categorization.", links: { bandcamp: "https://lorainejames.bandcamp.com" }, relatedArtists: [] },
  { slug: "huerco-s", name: "Huerco S.", bio: "Maryland's Brian Huerco Stanley crafts hyperverbal, texture-saturated ambient works. His studio is a palimpsest of acoustic and electronic sources, each layer adding to hypnotic depth.", links: { bandcamp: "https://huercosmusic.bandcamp.com" }, relatedArtists: [] },
  { slug: "the-caretaker", name: "The Caretaker", bio: "Leyland Kirby's Everywhere at the End of Time remains the most ambitious electronic music work about memory, loss, and decay. Beauty extracted from deteriorating vinyl.", links: { bandcamp: "https://thecaretaker.bandcamp.com" }, relatedArtists: ["william-basinski"] },
  { slug: "william-basinski", name: "William Basinski", bio: "Basinski's The Disintegration Loops transformed tape degradation into profoundly moving art. His work is about impermanence, memory, and the haunting beauty of things falling apart.", links: { bandcamp: "https://williambasinski.bandcamp.com" }, relatedArtists: ["the-caretaker"] },
  { slug: "fennesz", name: "Fennesz", bio: "Christian Fennesz's digital guitar processing turns six-string vibrations into spectral clouds of shimmer. His glitch-inflected beauty proves that distortion and electronics are instruments of grace.", links: { bandcamp: "https://fennesz.bandcamp.com" }, relatedArtists: ["tim-hecker", "jan-jelinek"] },
  { slug: "jan-jelinek", name: "Jan Jelinek", bio: "German laptop artist whose microsampled, cut-and-paste aesthetic predates glitch idiom. His work feels like overheard fragments stitched into hypnotic new coherence.", links: { bandcamp: "https://janjelinek.bandcamp.com" }, relatedArtists: ["fennesz"] },
  { slug: "gas", name: "GAS / Wolfgang Voigt", bio: "Wolfgang Voigt's GAS project strips techno to its essence: morphing sine waves, minimal percussion, maximum hypnosis. His Cologne Sound redefined what minimalism could accomplish on the dancefloor.", links: { bandcamp: "https://gasarchive.bandcamp.com" }, relatedArtists: [] },
  { slug: "jon-hopkins", name: "Jon Hopkins", bio: "Jon's minimalist ambience and polyrhythmic hyperactivity exist in strange communion. Emerald Rush and Immunity both proved electronic music could communicate profound emotional truth.", links: { website: "https://www.jonhopkins.co.uk" }, relatedArtists: ["rival-consoles"] },
  { slug: "rival-consoles", name: "Rival Consoles", bio: "Ryan Radcliffe merges modular synthesis with pop sensibility. His shimmering, arpeggiated soundscapes prove that electronic music can be both emotionally direct and technically intricate.", links: { bandcamp: "https://rivalconsoles.bandcamp.com" }, relatedArtists: ["jon-hopkins"] },
  { slug: "beatrice-dillon", name: "Beatrice Dillon", bio: "Dublin's Beatrice crafts polyrhythmic, spatially complex electronic music that feels architectural. Her restraint and precision have made her central to contemporary club and gallery contexts.", links: { bandcamp: "https://beatricedillon.bandcamp.com" }, relatedArtists: [] },

  // Featured
  { slug: "rykard", name: "Rykard", bio: "Rykard's self-released work captures the raw urgency of experimental techno and ambient. His vision of the future comes from the margins, uncompromising and deeply felt.", links: { label: "https://hunyamunya.com", bandcamp: "https://rykard.bandcamp.com" }, relatedArtists: [], featured: true },
];

export function getArtist(slug: string): ArtistData | undefined {
  return artists.find((a) => a.slug === slug);
}

export function getAllArtists(): ArtistData[] {
  return artists;
}

export function getFeaturedArtists(): ArtistData[] {
  return artists.filter((a) => a.featured);
}
