name = "phreak-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[triggers]
crons = ["*/30 * * * *"]

[[kv_namespaces]]
binding = "FEED_KV"
id = "fe98b85d318b4f9aa91568368e833d78"
preview_id = "fe98b85d318b4f9aa91568368e833d78"

[[kv_namespaces]]
binding = "CONTENT_KV"
id = "66ce6bac1df4451a92a602987d111a5e"
preview_id = "66ce6bac1df4451a92a602987d111a5e"

# R2 buckets (enable when ready for audio/media storage)
# [[r2_buckets]]
# binding = "AUDIO_R2"
# bucket_name = "phreak-audio"

# [[r2_buckets]]
# binding = "MEDIA_R2"
# bucket_name = "phreak-media"

[vars]
ENVIRONMENT = "production"
